#pragma once

// UN-DEFINES
//#undef PERMISSIVE_HOLD
#undef IGNORE_MOD_TAP_INTERRUPT
//#undef TAPPING_FORCE_HOLD
//#undef RETRO_TAPPING

#define PERMISSIVE_HOLD
//#define IGNORE_MOD_TAP_INTERRUPT
//#define TAPPING_FORCE_HOLD
//#define RETRO_TAPPING

//#define NO_ACTION_ONESHOT
//#define NO_ACTION_MACRO

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 2

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 10

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 1




